[package]
name = "eclipse-ibc-cli"
description = "Eclipse IBC CLI"
version = "0.1.0"
homepage = "https://eclipse.builders/"
repository = "https://github.com/Eclipse-Laboratories-Inc/ibc"
authors = ["Eclipse Developers"]
edition = "2021"

[dependencies]
anyhow = "1.0.70"
bincode = "1.3.3"
clap = { version = "4.2.1", features = ["derive"] }
eclipse-ibc-light-client = { path = "../light-client" }
eclipse-ibc-program = { path = "../program" }
eclipse-ibc-proto = { path = "../proto" }
eclipse-ibc-state = { path = "../state" }
ibc = "0.36.0"
ibc-proto = "0.26.0"
prost = "0.11.8"
serde = "1.0.159"
serde_json = "1.0.95"
solana-client = "=1.15.2"
solana-sdk = "=1.15.2"
tokio = { version = "1.27.0", features = ["full", "tracing"] }
